name: Build Geode Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check and Install Geode CLI
        run: |
          INSTALL_SCRIPT_URL="https://raw.githubusercontent.com/geode-sdk/cli/main/install.sh"
          echo "Checking ${INSTALL_SCRIPT_URL}"
          # try to fetch headers
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" "${INSTALL_SCRIPT_URL}")
          echo "HTTP status: ${HTTP_STATUS}"
          if [ "${HTTP_STATUS}" -ne 200 ]; then
            echo "Could not fetch install script: HTTP ${HTTP_STATUS}"
            exit 1
          fi
          # script seems to exist, download and run
          curl -sSL "${INSTALL_SCRIPT_URL}" | bash
          # ensure PATH includes user's local bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build
        run: geode build -p android64 --release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MegaHackOverlay
          path: dist/*.geode
