name: Build Geode Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Geode CLI using the official bootstrap script
      - name: Install Geode CLI
        run: |
          curl -sSL https://raw.githubusercontent.com/geode-sdk/cli/main/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build
        run: geode build -p android64 --release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MegaHackOverlay
          path: dist/*.geode
