name: Build Geode Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git unzip

      - name: Clone Geode CLI
        run: |
          git clone https://github.com/geode-sdk/cli.git
          # You may need to checkout a specific branch/tags if 'main' doesn't have code
          cd cli
          # Check if there is any install or build script
          if [ -f install.sh ]; then
            bash install.sh
          elif [ -f bootstrap.sh ]; then
            bash bootstrap.sh
          else
            echo "No install script found in cloned CLI repo. Listing files:"
            ls -R .
            exit 1
          fi
          # Make sure CLI is in PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          cd ..

      - name: Build the mod
        run: geode build -p android64 --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MegaHackOverlay
          path: dist/*.geode
