name: Build Geode Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python & Geode CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip cmake ninja-build
          pip3 install geode-sdk
      - name: Build
        run: geode build -p android64 --release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MegaHackOverlay
          path: dist/*.geode
